### ISSUE TITLE
Proxy Server

### ISSUE THREAD

**Issue by kevinshaffer** [waltfy/destiny#8]
Either I'm not setting Destiny to be looking at the correct place, or my proxy isn't working. Can you give slightly more detailed instructions on how to do this? (I'm an utter noob when it comes to node).

Right now I have the proxy set up and just running on my site's main directory, and then put my base url instead of your commented out localhost, but I'm fairly certain that's not correct. Any help would be great, thanks!

**Comment by waltfy** [comment]
If you are using the library on a server-side node application, you do not need to worry about doing this, at all. However, if you want to run the code on the client you must run the proxy server since Bungie will not accept origin requests originated from your website. 

So what you have to do, exactly, is:

1. Ensure the proxy is running by entering `node proxy.js 9000` on your terminal. This will start your proxy server on port 9000.
2. Once this is running and awaiting for requests, you must then initialise your client instance on your code, e.g. `var destiny = require('destiny-client')({ host: 'http://localhost:9000' });` note that the `host` attribute points at your proxy server.

**Comment by kevinshaffer** [comment]
Thank you very much for a quick response! I'll give it a try later today and hopefully get back with a success story. 

-Kevin Shaffer

**Comment by waltfy** [comment]
Worth noticing that if you deploy any page to an environment that isn't local. Make sure that your Destiny client instance uses the correct path under the same domain. For example:

http://www.mycoolthing.com – host
Make sure you initialise your client with the correct host i.e. `var client = Destiny({ host: 'http://www.mycoolthing.com:9000' });`
